spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafe_mgmt
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # or update / create / none depending on use case
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
#      schema-locations: classpath:schema.sql # if you're using schema files
#      data-locations: classpath:data.sql     # if you're loading test data

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
